export const tableData = [
  {
    invoice: 'Basic Plan - Dec 2022',
    amount: 10,
    date: 'Dec 1, 2022',
    status: 'paid',
    usersOnPlan: 7,
  },
  {
    invoice: 'Basic Plan - Nov 2022',
    amount: 10,
    date: 'Nov 1, 2022',
    status: 'paid',
    usersOnPlan: 2,
  },
  {
    invoice: 'Basic Plan - Oct 2022',
    amount: 10,
    date: 'Oct 1, 2022',
    status: 'paid',
    usersOnPlan: 5,
  },
  {
    invoice: 'Basic Plan - Sep 2022',
    amount: 10,
    date: 'Sep 1, 2022',
    status: 'paid',
    usersOnPlan: 4,
  },
  {
    invoice: 'Basic Plan - Aug 2022',
    amount: 10,
    date: 'Aug 1, 2022',
    status: 'paid',
    usersOnPlan: 5,
  },
  {
    invoice: 'Basic Plan - Jul 2022',
    amount: 10,
    date: 'Jul 1, 2022',
    status: 'paid',
    usersOnPlan: 1,
  },
  {
    invoice: 'Basic Plan - Jun 2022',
    amount: 10,
    date: 'Jun 1, 2022',
    status: 'paid',
    usersOnPlan: 7,
  },
];
